Dockerfile - 2 

FROM debian  

RUN apt-get update && apt-get install -y apache2 && apt-get clean 

ENV APACHE_LOCK_DIR="/var/lock" 

ENV APACHE_PID_FILE="/var/run/apache2.pid" 

ENV APACHE_RUN_USER="www-data" 

ENV APACHE_RUN_GROUP="www-data" 

ENV APACHE_LOG_DIR="/var/log/apache2"  

LABEL description="Webserver"  

 

VOLUME /var/www/html/ 

EXPOSE 80 

ENTRYPOINT ["/usr/sbin/apachectl"] 

CMD ["-D", "FOREGROUND"]                                                                                                                                                                          

OBS - 

Modo lista :  

ENTRYPOINT ["/usr/sbin/apachectl"] 

CMD ["-D", "FOREGROUND"] 

Modo Shell: 

CMD /usr/sbin/apachectl -D FOREGROUND 

Build image 

docker image build -t meu_apache:2.0.0 . --no-cache   

OBS: “--no-cache" parâmetro usado para montar imagem sem cache 

Criando container 

docker container run -d -p 8080:80 meu_apache:2.0.0 

 

Dockerfile - 2 

FROM debian 

  

RUN apt-get update && apt-get install -y apache2 && apt-get clean 

ENV APACHE_LOCK_DIR="/var/lock" 

ENV APACHE_PID_FILE="/var/run/apache2.pid" 

ENV APACHE_RUN_USER="www-data" 

ENV APACHE_RUN_GROUP="www-data" 

ENV APACHE_LOG_DIR="/var/log/apache2" 

COPY index.html  /var/www/html/                                                                                                                                       

LABEL description="Webserver" 

  

VOLUME /var/www/html/ 

EXPOSE 80 

  

ENTRYPOINT ["/usr/sbin/apachectl"] 

CMD ["-D", "FOREGROUND"] 
